# Generated by Django 4.2.26 on 2026-04-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_organization_chatsession_public_share_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
